"""Fix comments

Revision ID: 20c2a011f70d
Revises: ed547c227398
Create Date: 2023-11-28 16:03:29.252482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c2a011f70d'
down_revision: Union[str, None] = 'ed547c227398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reply_comments', 'parent_comment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reply_comments', 'parent_review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('reply_comments_parent_comment_id_fkey', 'reply_comments', type_='foreignkey')
    op.drop_constraint('reply_comments_parent_review_id_fkey', 'reply_comments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reply_comments_parent_review_id_fkey', 'reply_comments', 'reviews', ['parent_review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reply_comments_parent_comment_id_fkey', 'reply_comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reply_comments', 'parent_review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reply_comments', 'parent_comment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
