"""Second revision

Revision ID: cd7c3c7a4b41
Revises: 9c55c882b3ab
Create Date: 2023-11-16 17:41:39.463938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7c3c7a4b41'
down_revision: Union[str, None] = '9c55c882b3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_username_fkey', 'comments', type_='foreignkey')
    op.alter_column('films', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('films', 'premiere_world',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'is_planned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_abandoned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_postponed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'local_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('reply_comments', 'parent_comment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reply_comments', 'parent_review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('reply_comments_parent_comment_id_fkey', 'reply_comments', type_='foreignkey')
    op.drop_constraint('reply_comments_parent_review_id_fkey', 'reply_comments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reply_comments_parent_review_id_fkey', 'reply_comments', 'reviews', ['parent_review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reply_comments_parent_comment_id_fkey', 'reply_comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reply_comments', 'parent_review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reply_comments', 'parent_comment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'local_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('films', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_postponed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_abandoned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'is_planned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('films', 'premiere_world',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('comments_username_fkey', 'comments', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    # ### end Alembic commands ###
