"""add trailer_poster to films

Revision ID: ed547c227398
Revises: cd7c3c7a4b41
Create Date: 2023-11-19 12:03:20.051570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed547c227398'
down_revision: Union[str, None] = 'cd7c3c7a4b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('trailer_poster', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'films', ['trailer_poster'])
    op.create_foreign_key(None, 'reply_comments', 'reviews', ['parent_review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reply_comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply_comments', type_='foreignkey')
    op.drop_constraint(None, 'reply_comments', type_='foreignkey')
    op.drop_constraint(None, 'films', type_='unique')
    op.drop_column('films', 'trailer_poster')
    # ### end Alembic commands ###
